version: "3.8"

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

  mfdp-service:
    build: .
    command: gunicorn -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000 app.main:app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres

  telegram-bot:
    build: .
    container_name: telegram-bot
    command: python -m bot.bot
    env_file:
      - .env
    depends_on:
      - mfdp-service

  importer:
    build: .
    command: python import_csv.py
    volumes:
      - ./data:/usr/src/app/data
    env_file:
      - .env
    depends_on:
      - postgres

  model-worker:
    build: .
    container_name: model-worker
    command: python -m worker.model_worker
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres

volumes:
  postgres_data: